spring:
  application: 
    name: eureka-peer2
server:
  port: 9998 
eureka:
  instance:
    hostname: prod
  client: 
    ###检索服务
    fetch-registry: false
    ###是否将自己注册到eureka
    register-with-eureka: false
    service-url: 
      defaultZone: http://localhost:9998/eureka/
  server:
    ###当eureka启动时，不能从集群节点中获取到instance注册信息，应该等多久
    wait-time-in-ms-when-sync-empty: 0
    ###eureka多长时间更新一次数据
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 100000 